name = "ICNBenchmarks"
uuid = "7d4a60b7-6f97-4d93-8ece-c2667b1c39e3"
authors = ["Jean-François BAFFIER", "Khalil CHRIT", "Florian RICHOUX", "Pedro PATINHO", "Salvador ABREU"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CompositionalNetworks = "4b67e4b5-442d-4ef5-b760-3f5df3a57537"
ConstraintDomains = "5800fd60-8556-4464-8d61-84ebf7a0bedb"
Constraints = "30f324ab-b02d-43f0-b619-e131c61659f7"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
BenchmarkTools = "1"
CSV = "0.9"
CompositionalNetworks = "0.2"
ConstraintDomains = "0.2"
Constraints = "0.2"
DrWatson = "2"
JSON = "0.21"
Tables = "1"
julia = "1.7"
