name = "ICN benchmarks"
authors = ["Jean-François BAFFIER", "Khalil CHRIT", "Florian RICHOUX", "Pedro PATINHO", "Salvador ABREU"]
[compat]
julia = "1.7.0"
DrWatson = "2.4.0"
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
